# WHEEL_0:
#   ID: 1
#   Return_Delay_Time: 0
#   Operating_Mode: 1
# WHEEL_1:
#   ID: 2
#   Return_Delay_Time: 0
#   Operating_Mode: 1
# WHEEL_2:
#   ID: 3
#   Return_Delay_Time: 0
#   Operating_Mode: 1
# WHEEL_3:
#   ID: 4
#   Return_Delay_Time: 0
#   Operating_Mode: 1
LINK_0:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
LINK_1:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 3
LINK_2:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 3
LINK_3:
  ID: 13
  Return_Delay_Time: 0
  Operating_Mode: 3